# -*- coding: utf-8 -*-
"""Training script for the Variational Junction‑Tree Molecular Encoder (VJTVAE).

The script expects a CSV with a ``selfies`` column (generated by
``prepare_egfr_dataset.py``).  It builds a simple token vocabulary, creates a
PyTorch ``Dataset`` that yields ``(selfies_tensor, descriptor_tensor)`` pairs,
and trains the ``VariationalJTVAE`` model defined in
``backend/generation/variational_jtvae.py``.

Usage example::

    python scripts/train_jtvae.py \
        --data datasets/external/chembl/processed/EGFR_selfies_train.csv \
        --val-data datasets/external/chembl/processed/EGFR_selfies_val.csv \
        --epochs 30 \
        --batch-size 128 \
        --latent-dim 128

The script will:
    * Detect a CUDA GPU (e.g., GTX 1050 Ti) and fall back to CPU.
    * Save the best checkpoint (lowest validation loss) to ``models/vjtv.pt``.
    * Log training/validation loss per epoch to ``logs/train_vjtv.log``.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from pathlib import Path
# Add project root (two levels up) to PYTHONPATH for absolute imports like 'backend.*'
project_root = Path(__file__).resolve().parents[1]
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from typing import Tuple, List

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from backend.generation.variational_jtvae import VariationalJTVAE
from backend.generation.selfies_converter import selfies_to_smiles
from rdkit import Chem

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def build_vocab(df: pd.DataFrame) -> Tuple[dict, dict]:
    """Build a token ↔ index mapping from the ``selfies`` column.
    Returns ``vocab, inverse_vocab``.
    """
    tokens = set()
    for s in df["selfiles"] if "selfiles" in df.columns else df["selfies"]:
        tokens.update(list(s))
    # Add a padding token
    vocab = {"[PAD]": 0, "[UNK]": 1}
    for i, t in enumerate(sorted(tokens), start=2):
        vocab[t] = i
    inverse = {i: t for t, i in vocab.items()}
    return vocab, inverse


def tokenise_selfies(s: str, vocab: dict) -> List[int]:
    """Convert a SELFIES string to a list of token IDs.
    Unknown characters become ``[UNK]`` (ID=1)."""
    return [vocab.get(ch, vocab["[UNK]"]) for ch in s]

# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------
class EGFRDataset(Dataset):
    def __init__(self, csv_path: pathlib.Path, vocab: dict | None = None, max_len: int = 256):
        self.df = pd.read_csv(csv_path)
        if "selfiles" in self.df.columns:  # typo safety
            self.df.rename(columns={"selfiles": "selfies"}, inplace=True)
        self.max_len = max_len
        self.vocab = vocab or self._build_vocab()
        # Pre‑compute descriptor vectors (used as regression targets)
        self.descriptors = []
        for smiles in self.df["smiles"]:
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                # Should never happen – dataset was validated earlier
                self.descriptors.append(np.zeros(5, dtype=np.float32))
                continue
            # Same descriptor set as used in ``variational_jtvae._compute_descriptors``
            wt = Chem.Descriptors.MolWt(mol) / 100.0
            logp = Chem.Descriptors.MolLogP(mol)
            hbd = Chem.Descriptors.NumHDonors(mol)
            hba = Chem.Descriptors.NumHAcceptors(mol)
            rot = Chem.Descriptors.NumRotatableBonds(mol)
            self.descriptors.append(np.array([wt, logp, hbd, hba, rot], dtype=np.float32))

    def _build_vocab(self) -> dict:
        tokens = set()
        for s in self.df["selfies"]:
            tokens.update(list(s))
        vocab = {"[PAD]": 0, "[UNK]": 1}
        for i, t in enumerate(sorted(tokens), start=2):
            vocab[t] = i
        return vocab

    def __len__(self) -> int:
        return len(self.df)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        row = self.df.iloc[idx]
        token_ids = tokenise_selfies(row["selfies"], self.vocab)
        # Pad / truncate to max_len
        if len(token_ids) < self.max_len:
            token_ids = token_ids + [self.vocab["[PAD]"]] * (self.max_len - len(token_ids))
        else:
            token_ids = token_ids[: self.max_len]
        selfies_tensor = torch.tensor(token_ids, dtype=torch.long)
        descriptor_tensor = torch.tensor(self.descriptors[idx], dtype=torch.float32)
        return selfies_tensor, descriptor_tensor

# ---------------------------------------------------------------------------
# Training utilities
# ---------------------------------------------------------------------------
def collate_fn(batch):
    selfies_batch, desc_batch = zip(*batch)
    selfies_batch = torch.stack(selfies_batch)
    desc_batch = torch.stack(desc_batch)
    return selfies_batch, desc_batch

def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    beta: float,
) -> Tuple[float, float]:
    model.train()
    total_loss = 0.0
    total_kl = 0.0
    total_reg = 0.0
    for selfies_batch, desc_batch in loader:
        selfies_batch = selfies_batch.to(device)
        desc_batch = desc_batch.to(device)
        # Decode each SELFIES to SMILES on‑the‑fly (cheap) and then to RDKit Mol
        mols = []
        for seq in selfies_batch:
            # Convert token IDs back to string (skip padding/unk)
            chars = [
                model.vocab_inv[t.item()] for t in seq if t.item() not in (model.vocab["[PAD]"], model.vocab["[UNK]"])
            ]
            s = "".join(chars)
            try:
                smiles = selfies_to_smiles(s)
                mol = Chem.MolFromSmiles(smiles)
            except Exception:
                mol = None
            if mol is None:
                # Substitute a single carbon atom – ensures the forward pass works
                mol = Chem.MolFromSmiles("C")
            mols.append(mol)
        mu, logvar, pred_desc = model.forward_batch(mols)
        # KL loss (mean over batch)
        kl = model.compute_kl(mu, logvar)
        reg = model.compute_regression_loss(pred_desc, desc_batch)
        loss = reg + beta * kl
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * len(mols)
        total_kl += kl.item() * len(mols)
        total_reg += reg.item() * len(mols)
    n = len(loader.dataset)
    return total_loss / n, total_reg / n, total_kl / n

def evaluate(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    beta: float,
) -> Tuple[float, float, float]:
    model.eval()
    total_loss = 0.0
    total_kl = 0.0
    total_reg = 0.0
    with torch.no_grad():
        for selfies_batch, desc_batch in loader:
            selfies_batch = selfies_batch.to(device)
            desc_batch = desc_batch.to(device)
            mols = []
            for seq in selfies_batch:
                chars = [
                    model.vocab_inv[t.item()] for t in seq if t.item() not in (model.vocab["[PAD]"], model.vocab["[UNK]"])
                ]
                s = "".join(chars)
                try:
                    smiles = selfies_to_smiles(s)
                    mol = Chem.MolFromSmiles(smiles)
                except Exception:
                    mol = None
                if mol is None:
                    mol = Chem.MolFromSmiles("C")
                mols.append(mol)
            mu, logvar, pred_desc = model.forward_batch(mols)
            kl = model.compute_kl(mu, logvar)
            reg = model.compute_regression_loss(pred_desc, desc_batch)
            loss = reg + beta * kl
            total_loss += loss.item() * len(mols)
            total_kl += kl.item() * len(mols)
            total_reg += reg.item() * len(mols)
    n = len(loader.dataset)
    return total_loss / n, total_reg / n, total_kl / n

# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Train VJTVAE on ChemBL EGFR dataset")
    parser.add_argument("--data", type=str, required=True, help="Path to training CSV (must contain 'selfies' column)")
    parser.add_argument("--val-data", type=str, required=True, help="Path to validation CSV")
    parser.add_argument("--epochs", type=int, default=30, help="Number of training epochs")
    parser.add_argument("--batch-size", type=int, default=128, help="Batch size")
    parser.add_argument("--latent-dim", type=int, default=128, help="Latent space dimensionality")
    parser.add_argument("--beta", type=float, default=0.1, help="Weight for KL term")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--max-len", type=int, default=256, help="Maximum SELFIES length (padding/truncation)")
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Using device: {device}")

    train_path = pathlib.Path(args.data)
    val_path = pathlib.Path(args.val_data)

    # Build a shared vocabulary from training data
    train_df = pd.read_csv(train_path)
    vocab, vocab_inv = build_vocab(train_df)

    # Attach vocab to model for convenience (used in training loop)
    model = VariationalJTVAE(latent_dim=args.latent_dim).to(device)
    model.vocab = vocab
    model.vocab_inv = vocab_inv
    # Add helper for batch forward (list of RDKit mols)
    def forward_batch(self, mols: List[Chem.Mol]):
        # Convert list of Mol to tensors inside the model's forward implementation
        # This helper simply re‑uses the same logic as ``forward`` but accepts a list.
        node_feats_list = []
        edge_idx_list = []
        for mol in mols:
            nf, ei = self._mol_to_graph(mol)
            node_feats_list.append(nf)
            edge_idx_list.append(ei)
        # Process each graph independently (batch size is modest, so a loop is fine)
        mus, logvars, preds = [], [], []
        for nf, ei in zip(node_feats_list, edge_idx_list):
            nf = nf.to(device)
            ei = ei.to(device)
            h = self.node_encoder(nf)
            for _ in range(self.mp_steps):
                src, dst = ei
                msg = h[src]
                agg = torch.zeros_like(h)
                agg = agg.index_add(0, dst, msg)
                h = self.message_mlp(agg + h)
            g = torch.sum(h, dim=0)
            g = torch.relu(self.graph_proj(g))
            mu = self.fc_mu(g)
            logvar = self.fc_logvar(g)
            std = torch.exp(0.5 * logvar)
            eps = torch.randn_like(std)
            z = mu + eps * std
            pred = self.descriptor_head(z)
            mus.append(mu)
            logvars.append(logvar)
            preds.append(pred)
        mu = torch.stack(mus)
        logvar = torch.stack(logvars)
        pred = torch.stack(preds)
        return mu, logvar, pred
    # Bind the helper method dynamically
    from types import MethodType
    model.forward_batch = MethodType(forward_batch, model)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    train_dataset = EGFRDataset(train_path, vocab=vocab, max_len=args.max_len)
    val_dataset = EGFRDataset(val_path, vocab=vocab, max_len=args.max_len)
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, collate_fn=collate_fn)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False, collate_fn=collate_fn)

    best_val_loss = float("inf")
    log_path = pathlib.Path("logs/train_vjtv.log")
    log_path.parent.mkdir(parents=True, exist_ok=True)

    with open(log_path, "w") as log_f:
        log_f.write("epoch,train_loss,train_reg,train_kl,val_loss,val_reg,val_kl\n")
        for epoch in range(1, args.epochs + 1):
            train_loss, train_reg, train_kl = train_one_epoch(
                model, train_loader, optimizer, device, args.beta
            )
            val_loss, val_reg, val_kl = evaluate(model, val_loader, device, args.beta)
            log_f.write(
                f"{epoch},{train_loss:.6f},{train_reg:.6f},{train_kl:.6f},{val_loss:.6f},{val_reg:.6f},{val_kl:.6f}\n"
            )
            log_f.flush()
            print(
                f"Epoch {epoch:02d} | Train loss {train_loss:.4f} (reg {train_reg:.4f}, kl {train_kl:.4f}) | "
                f"Val loss {val_loss:.4f} (reg {val_reg:.4f}, kl {val_kl:.4f})"
            )
            # Save checkpoint if validation improves
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                ckpt_path = pathlib.Path("models/vjtv.pt")
                ckpt_path.parent.mkdir(parents=True, exist_ok=True)
                torch.save(
                    {
                        "model_state_dict": model.state_dict(),
                        "vocab": vocab,
                        "latent_dim": args.latent_dim,
                    },
                    ckpt_path,
                )
                print(f"[INFO] Saved new best checkpoint to {ckpt_path}")

    # Save final metadata JSON for downstream services
    meta = {
        "latent_dim": args.latent_dim,
        "vocab_size": len(vocab),
        "max_len": args.max_len,
        "device": str(device),
        "beta": args.beta,
    }
    meta_path = pathlib.Path("models/vjtv_metadata.json")
    with open(meta_path, "w") as mf:
        json.dump(meta, mf, indent=2)
    print(f"[INFO] Training complete. Metadata written to {meta_path}")


if __name__ == "__main__":
    main()
